### ISSUE TITLE
Docker daemon responds slowly and has errors when too many images on the host

### ISSUE THREAD

**Issue by supereagle** [supereagle/experience#2]
When there are about 1K images on the Docker host, I found two problems:
* Wait about 30 seconds to start push image after run `docker push` command
* Containers can not be removed immediately, and Docker daemon has errors: 
```
# docker rm -f c44ec3f542f0
Failed to remove container (c44ec3f542f0): Error response from daemon: Could not kill running container, cannot remove - [2] Container does not exist: container destroyed
```

**Comment by supereagle** [comment]
### Solution
Use cron job to clean the images satisfy conditions:
* 10 days ago
* Not used by running containers

**Cron Job Configure:**
```
0 1 * * * docker rmi -f $(docker images | grep 'months ago\|weeks ago\|1[0-9] days ago' | awk '{ print $3 }') >/dev/null 2>&1
```

**Comment by supereagle** [comment]
### Enhancement

Use Ansible Cron module to add clean cron job for all K8s nodes in batch
* k8s-nodes-cron.yml
```yml
- hosts: k8s-nodes
  roles:
    - { role: 'k8s-nodes-cron', tags: 'k8s-nodes-cron' }
```

* roles/k8s-nodes-cron/tasks/main.yml
```yml
---
- name: Create image clean cron job
  cron: name="Clean images" minute="0" hour="1" day="*" month="*" weekday="*" job="docker rmi -f $(docker images | grep 'months ago\|weeks ago\|1[0-9] days ago' | awk '{ print $3 }') >/dev/null 2>&1"
```
